### ISSUE TITLE
Don't open deleted files

### ISSUE THREAD

**Issue by cshold** [chrisbutcher/sublime3-gitopenchangedfiles#2]
Hey, great helper. Only suggestion is to ignore deleted files. Currently it opens a blank file with that name.

Cheers

**Comment by chrisbutcher** [comment]
Thanks! @cshold. I have actually addressed this issue in a recent commit (https://github.com/chrisbutcher/sublime3-gitopenchangedfiles/blob/master/GitOpenChangedFiles.py#L49), you can cd into the repo and git pull to get the change.

Also note, I'm going to be publishing this plugin to the Sublime Package Control repo soon (https://github.com/wbond/package_control_channel/pull/4400), so you'll be able to reinstall the plugin via that, and keep it in sync via the Upgrade command.

**Comment by cshold** [comment]
Excellent, thanks!
